// Copyright (C) 1991-2015 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus II License Agreement,
// the Altera MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Altera and sold by Altera or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus II 64-Bit Version 15.0 (Build Build 145 04/22/2015)
// Created on Mon Jun 19 18:37:10 2017

ALU ALU_inst
(
	.A(A_sig) ,	// input [7:0] A_sig
	.B(B_sig) ,	// input [7:0] B_sig
	.F(F_sig) ,	// output [7:0] F_sig
	.SSEL(SSEL_sig) ,	// input [3:0] SSEL_sig
	.Z(Z_sig) ,	// output  Z_sig
	.S(S_sig) ,	// output  S_sig
	.C(C_sig) ,	// output  C_sig
	.V(V_sig) 	// output  V_sig
);

