// Copyright (C) 1991-2015 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus II License Agreement,
// the Altera MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Altera and sold by Altera or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus II 64-Bit Version 15.0 (Build Build 145 04/22/2015)
// Created on Wed Jun 21 13:34:36 2017

carMux1Mux2 carMux1Mux2_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.Z(Z_sig) ,	// input  Z_sig
	.S(S_sig) ,	// input  S_sig
	.C(C_sig) ,	// input  C_sig
	.V(V_sig) ,	// input  V_sig
	.internalAddress(internalAddress_sig) ,	// input [7:0] internalAddress_sig
	.externalAddress(externalAddress_sig) ,	// input [7:0] externalAddress_sig
	.mux1Select(mux1Select_sig) ,	// input  mux1Select_sig
	.mux2Select(mux2Select_sig) ,	// input [2:0] mux2Select_sig
	.outputAddress(outputAddress_sig) 	// output [7:0] outputAddress_sig
);

